### PR TITLE
okhttp2 to okhttp3

### PR DESCRIPTION
**Pull request by kepuss**
Hi

Because in open-keychain was change in okhttp2 the urlfactory is deprecated so I changed it to okhttpconnection and removed DefaultKeybaseUrlConnectionClient because unused after consult with @dschuermann in  #1775

### CODE REVIEW

**Comment by dschuermann** [comment]
Hey @kepuss , thanks for your work!
I think there were some smaller misunderstanding. I'd like to keep the KeybaseLib free of OkHttp dependency. That's why it was designed with the interface KeybaseUrlConnectionClient which can be implemented by different http libraries.

A similar example is the Downloader class in Picasso, see https://github.com/square/picasso/blob/851a3de739a2de5d0112f188fcdc232be56a25a0/picasso/src/main/java/com/squareup/picasso/Downloader.java which is implemented by https://github.com/square/picasso/blob/851a3de739a2de5d0112f188fcdc232be56a25a0/picasso/src/main/java/com/squareup/picasso/OkHttp3Downloader.java but also https://github.com/square/picasso/blob/851a3de739a2de5d0112f188fcdc232be56a25a0/picasso/src/main/java/com/squareup/picasso/UrlConnectionDownloader.java

Can you rework KeybaseLib to be independent of the http library and remove the dependency on okhttp? Then (similar to before) OpenKeychain should contain one class implementing the interface with okhttp3.

Please feel free to ask questions if anything is unclear! :)

**Comment by kepuss** [comment]
Sure, I was little confused about KeybaseLib. Ok, I'll be back with solution or more questions :)

**Comment by dschuermann** [comment]
@kepuss How is the progress? :)

**Comment by kepuss** [comment]
Sorry for big delay, I had some thing to complete at Uni.
So which solution would be better:
First:
1. KebaseLib stays untouched 
2. OkHttpKeybaseClient implements KeybaseUrlConnectionClient and is developed with okhttp3 with deprecated OkUrlFactory ( will be removed).

Second:
1. Create wrapper for KebaseLib response, simillar as the one in Picasso (no http3 dependency)
2. OkHttpKeybaseClient  implemented with okhttp2 client

I suppose the second one, am I right?

**Comment by dschuermann** [comment]
@kepuss Nice, yup, second option is preferred by me :)

**Pull request closed without merging**
